config/routes.rb
Domainchecker::Application.routes.draw do
  root 'domains#index'
  resources :domains

  

end

app/models/concerns/domain_expired.rb
module DomainExpired
  extend ActiveSupport::Concern
  
  def check_expiry
    whois = check_domain(self.name)
    self.expiry_date = whois["properties"]["expires_on"]
    save!
  end
  
  private
    def check_domain(domain_name)
      client = RoboWhois.new(:api_key => 'df81f69f0e2698ca5fb84a1c051aef82')
      response = client.whois_properties(domain_name)
    end
end

app/models/domain.rb
class Domain < ActiveRecord::Base

  include DomainExpired

  validates_presence_of :name
  validates_format_of :name, :with => /\A[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\Z/i , :message => "invalide domain name"

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  def index
    @domains = Domain.all.order("id DESC")
    @domain = Domain.new
  end

  def new
    @domain = Domain.new
  end

  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        @domain.check_expiry
        format.html { redirect_to domains_url, notice: 'Domain was successfully created.' }
        format.json { render action: 'show', status: :created, location: @domain }
      else
        format.html { render action: 'new' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :no_content }
    end
  end

  private
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:name, :expiry_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_expiry_color.html.erb
<% if expiry_date > Date.today && expiry_date <  3.week.from_now %>
  <div class="expiry_color red"></div>
<% elsif expiry_date > Date.today && expiry_date < 3.month.from_now %>
  <div class="expiry_color orange"></div>
<% elsif expiry_date > Date.today && expiry_date < 6.month.from_now %>
  <div class="expiry_color yellow"></div>
<% elsif expiry_date > 6.month.from_now %>
  <div class="expiry_color green"></div>
<% end %>

app/views/domains/_form.html.erb
<%= simple_form_for(@domain, html: {class: 'form-inline' }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name, :input_html => { :class => "span8 input-large" }, :label => false, :placeholder => "Enter a domain name" %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<div class="container">
<div class="row">
  <div class="span12 center"><%= render 'form' %>
</div>
<ul class="row domains">
  <% @domains.each do |domain| %>
    <li class="span10 offset1">
    <% if domain.expiry_date %><%= render 'expiry_color', :expiry_date => domain.expiry_date %><% end %>
      <h3><%= domain.name %></h3>
      <div class="expiry-date"><%= domain.expiry_date%></div>
      <div class="controls">
        <%= link_to 'Delete',
                    domain_path(domain),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>
      </div>
    </li>
  <% end %>
</ul>


</div><!-- container -->

app/views/domains/new.html.erb
<div class="container">
	<div class="row  well">
		<div class="span8">
      <h2 class="offset2">New Domain</h2>
			<%= render 'form' %>
    </div>
  </div>
</div>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @domain.name %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @domain.expiry_date %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Domain Checker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
 <%= csrf_meta_tags %>
  
  <script type="text/javascript" src="//use.typekit.net/urf5uuz.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>
  <div class="container">
  <% flash.each do |name, msg| %>
  	<div class="animated bounceInDown alert alert-<%= name == :notice ? "success" : "error" %>">
  		<button type="button" class="close" data-dismiss="alert">&times;</button>
  		<%= msg %>
  	</div>
  <% end %>
  </div>

	 
<%= yield %>
<footer>
  <p class="center">Copyright © 2013 Bassem Shaker. All Rights Reserved</p>
</footer>
</body>
</html>